_wandb:
    value:
        cli_version: 0.26.1
        e:
            8nikof5hq8posjhx9dr8763yw6454lb4:
                cpu_count: 20
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "138224336896"
                        used: "108471255040"
                executable: /home/ubuntu/miniforge3/bin/python
                git:
                    commit: 7e61b3e7fa9cfe242ea31adb9598c8f9c64235da
                    remote: git@github.com:WANGJINYU0711/PSAgent.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-a06b304b-169b-362b-19d1-2ff61c3ffd9d
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-9e57eda1-041c-ed8b-5964-f731b86c15cc
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-50ad325e-5f89-d502-43c7-38d36449b0ac
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-1f14b01f-d55b-395e-eb5a-a12737db78f6
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-3f5a47e4-a6e5-77c5-3893-92be5786645b
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-2d8812aa-1afc-a8a8-d710-3cdd5263a129
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-a3c52f97-48b1-b196-e78b-5279bb530b2b
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-7d8034d3-4209-f308-16b4-8be5608d738e
                host: wangjinyu
                memory:
                    total: "107374182400"
                os: Linux-5.13.0-30-generic-x86_64-with-glibc2.31
                program: <stdin>
                python: CPython 3.13.12
                root: /home/ubuntu/data/PSAgent
                startedAt: "2026-04-30T13:45:19.230159Z"
                writerId: 8nikof5hq8posjhx9dr8763yw6454lb4
        m: []
        python_version: 3.13.12
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.26.1
            "8":
                - 2
            "12": 0.26.1
            "13": linux-x86_64
dataset:
    value: local_exec_clean_v2_100
epsilon:
    value: 0.01
eta:
    value: 0.3
experiment_name:
    value: llm_v8_stage45_contract_promptv11b_stage45_gpt41mini_cconfig_d4_eta03_eps001_10x10_3methods_seed0_seed1
methods:
    value:
        - risky_ps
        - direct_multistage_exp3
        - epsilon_exp3
prompt_version:
    value: stage45_contract_prompt_v1_1b
seeds:
    value:
        - 0
        - 1
stage45_model:
    value: gpt-4.1-mini
stage123_model:
    value: gpt-4o-mini
switch_denominator:
    value: 4
