"""Preset configurations for neutral / moderate / strong tree families."""

from __future__ import annotations


def build_neutral_family_spec() -> dict:
    return {
        "family_name": "neutral",
        "stages": ["stage1", "stage2", "stage3", "stage4", "stage5"],
        "num_agents_per_stage": 3,
        "g1_per_stage": {"stage1": 1, "stage2": 1, "stage3": 1, "stage4": 1, "stage5": 1},
        "competence_per_stage": {"high": 1, "low": 2},
        "scope_per_stage": {"broad": 2, "narrow": 1},
        "stability_per_stage": {"stable": 2, "unstable": 1},
        "skill_ranges": {
            "broad": (0.55, 0.70),
            "narrow_focus": (0.70, 0.80),
            "narrow_other": (0.35, 0.50),
            "high_bonus": 0.10,
        },
        "cost_ranges": {
            "safe": (0.08, 0.12),
            "special": (0.12, 0.16),
        },
    }


def build_moderate_family_spec() -> dict:
    return {
        "family_name": "moderate",
        "stages": ["stage1", "stage2", "stage3", "stage4", "stage5"],
        "num_agents_per_stage": 4,
        "g1_per_stage": {"stage1": 2, "stage2": 2, "stage3": 2, "stage4": 2, "stage5": 2},
        "competence_per_stage": {"high": 2, "low": 2},
        "scope_per_stage": {"broad": 2, "narrow": 2},
        "stability_per_stage": {"stable": 2, "unstable": 2},
        "skill_ranges": {
            "broad": (0.55, 0.75),
            "narrow_focus": (0.85, 0.95),
            "narrow_other": (0.25, 0.50),
            "high_bonus": 0.10,
        },
        "cost_ranges": {
            "safe": (0.08, 0.12),
            "special": (0.15, 0.22),
        },
    }


def build_strong_family_spec() -> dict:
    return {
        "family_name": "strong",
        "generation_mode": "legacy_attribute_ranges",
        "stages": ["stage1", "stage2", "stage3", "stage4", "stage5"],
        "num_agents_per_stage": 4,
        "g1_per_stage": {"stage1": 1, "stage2": 2, "stage3": 2, "stage4": 3, "stage5": 3},
        "competence_per_stage": {"high": 2, "low": 2},
        "scope_per_stage": {"broad": 1, "narrow": 3},
        "stability_per_stage": {"stable": 2, "unstable": 2},
        "skill_ranges": {
            "broad": (0.55, 0.72),
            "narrow_focus": (0.90, 1.00),
            "narrow_other": (0.15, 0.45),
            "high_bonus": 0.10,
        },
        "cost_ranges": {
            "safe": (0.08, 0.14),
            "special": (0.18, 0.28),
        },
    }


def build_shared_basin_strong_family_spec() -> dict:
    return {
        "family_name": "shared_basin_strong",
        "generation_mode": "capability_shared_basin",
        "stages": ["stage1", "stage2", "stage3", "stage4", "stage5"],
        "num_agents_per_stage": 5,
        "profile_fields": {
            "competence_level": "capability",
            "scope_level": "capability",
            "stability_level": "capability",
        },
        "cost_ranges": {
            "uniform": (0.12, 0.16),
        },
        "shared_skill_ranges": {
            "anchor": (0.82, 0.94),
            "support": (0.5, 0.66),
            "background": (0.14, 0.28),
        },
        "shared_focus_fallback_range": (0.47, 0.61),
        "specialist_skill_ranges": {
            "anchor": (0.96, 1.0),
            "support": (0.24, 0.42),
            "background": (0.02, 0.12),
        },
        "stage_profiles": {
            "stage1": [
                {
                    "role": "shared_core",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "allowed_next_labels": ["core"],
                    "anchor_caps": ["user_grounding", "account_lookup", "line_resolution"],
                    "support_caps": ["verification"],
                },
                {
                    "role": "shared_grounding",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "allowed_next_labels": ["core"],
                    "anchor_caps": ["user_grounding", "line_resolution"],
                    "support_caps": ["account_lookup", "verification"],
                },
                {
                    "role": "shared_lookup",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed", "specialist"],
                    "anchor_caps": ["account_lookup", "line_resolution"],
                    "support_caps": ["user_grounding"],
                },
                {
                    "role": "shared_hard_context",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed", "specialist"],
                    "anchor_caps": ["user_grounding", "verification"],
                    "support_caps": ["line_resolution"],
                },
                {
                    "role": "ambiguity_specialist",
                    "g": 1,
                    "profile_kind": "specialist",
                    "route_label": "specialist",
                    "allowed_next_labels": ["mixed", "specialist"],
                    "anchor_caps": ["line_resolution", "verification"],
                    "support_caps": ["account_lookup"],
                },
            ],
            "stage2": [
                {
                    "role": "shared_account_core",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "allowed_next_labels": ["core"],
                    "anchor_caps": ["account_lookup", "line_resolution"],
                    "support_caps": ["roaming_diagnosis"],
                },
                {
                    "role": "shared_line_core",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "allowed_next_labels": ["core"],
                    "anchor_caps": ["account_lookup", "line_resolution"],
                    "support_caps": ["roaming_diagnosis"],
                },
                {
                    "role": "shared_account_alt",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed", "specialist"],
                    "anchor_caps": ["account_lookup", "line_resolution"],
                    "support_caps": ["terminal_decision"],
                },
                {
                    "role": "shared_roaming_ready",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed", "specialist"],
                    "anchor_caps": ["roaming_diagnosis", "account_lookup"],
                    "support_caps": ["line_resolution"],
                },
                {
                    "role": "roaming_specialist",
                    "g": 1,
                    "profile_kind": "specialist",
                    "route_label": "specialist",
                    "allowed_next_labels": ["mixed", "specialist"],
                    "anchor_caps": ["roaming_diagnosis"],
                    "support_caps": ["account_lookup", "line_resolution"],
                },
            ],
            "stage3": [
                {
                    "role": "shared_network_core",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "allowed_next_labels": ["core"],
                    "anchor_caps": ["network_diagnosis"],
                    "support_caps": [
                        "permission_diagnosis",
                        "apn_diagnosis",
                        "roaming_diagnosis",
                    ],
                },
                {
                    "role": "shared_permission_support",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "allowed_next_labels": ["core"],
                    "anchor_caps": ["network_diagnosis", "permission_diagnosis"],
                    "support_caps": ["verification"],
                },
                {
                    "role": "shared_apn_support",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed"],
                    "anchor_caps": ["apn_diagnosis", "network_diagnosis"],
                    "support_caps": ["verification"],
                },
                {
                    "role": "shared_roaming_support",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed"],
                    "anchor_caps": ["network_diagnosis", "roaming_diagnosis"],
                    "support_caps": ["verification"],
                },
                {
                    "role": "edge_config_specialist",
                    "g": 1,
                    "profile_kind": "specialist",
                    "route_label": "specialist",
                    "allowed_next_labels": ["mixed"],
                    "anchor_caps": ["network_diagnosis", "apn_diagnosis", "roaming_diagnosis"],
                    "support_caps": [],
                },
            ],
            "stage4": [
                {
                    "role": "shared_repair_core",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "allowed_next_labels": ["core"],
                    "anchor_caps": ["repair_execution"],
                    "support_caps": [
                        "network_diagnosis",
                        "permission_diagnosis",
                        "apn_diagnosis",
                    ],
                },
                {
                    "role": "shared_repair_network",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "allowed_next_labels": ["core"],
                    "anchor_caps": ["repair_execution", "network_diagnosis"],
                    "support_caps": ["verification"],
                },
                {
                    "role": "shared_repair_config",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed", "specialist"],
                    "anchor_caps": ["repair_execution", "permission_diagnosis", "apn_diagnosis"],
                    "support_caps": [],
                },
                {
                    "role": "shared_repair_roaming",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed", "specialist"],
                    "anchor_caps": ["repair_execution", "roaming_diagnosis"],
                    "support_caps": ["network_diagnosis", "terminal_decision"],
                },
                {
                    "role": "shared_repair_extreme_config",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "allowed_next_labels": ["core", "mixed", "specialist"],
                    "anchor_caps": ["repair_execution", "apn_diagnosis", "roaming_diagnosis"],
                    "support_caps": ["network_diagnosis"],
                },
            ],
            "stage5": [
                {
                    "role": "shared_verify_core",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "anchor_caps": ["verification", "terminal_decision"],
                    "support_caps": ["repair_execution"],
                },
                {
                    "role": "shared_verify_lean",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "anchor_caps": ["verification"],
                    "support_caps": ["terminal_decision", "repair_execution"],
                },
                {
                    "role": "shared_decision_lean",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "core",
                    "anchor_caps": ["terminal_decision"],
                    "support_caps": ["verification", "repair_execution"],
                },
                {
                    "role": "shared_transfer_ready",
                    "g": 0,
                    "profile_kind": "shared_basin",
                    "route_label": "mixed",
                    "anchor_caps": ["terminal_decision", "verification"],
                    "support_caps": ["repair_execution"],
                },
                {
                    "role": "transfer_specialist",
                    "g": 1,
                    "profile_kind": "specialist",
                    "route_label": "specialist",
                    "anchor_caps": ["terminal_decision"],
                    "support_caps": ["verification"],
                },
            ],
        },
    }
