"""Preset configurations for neutral / moderate / strong tree families."""

from __future__ import annotations


def build_neutral_family_spec() -> dict:
    return {
        "family_name": "neutral",
        "stages": ["stage1", "stage2", "stage3", "stage4", "stage5"],
        "num_agents_per_stage": 3,
        "g1_per_stage": {"stage1": 1, "stage2": 1, "stage3": 1, "stage4": 1, "stage5": 1},
        "competence_per_stage": {"high": 1, "low": 2},
        "scope_per_stage": {"broad": 2, "narrow": 1},
        "stability_per_stage": {"stable": 2, "unstable": 1},
        "skill_ranges": {
            "broad": (0.55, 0.70),
            "narrow_focus": (0.70, 0.80),
            "narrow_other": (0.35, 0.50),
            "high_bonus": 0.10,
        },
        "cost_ranges": {
            "safe": (0.08, 0.12),
            "special": (0.12, 0.16),
        },
    }


def build_moderate_family_spec() -> dict:
    return {
        "family_name": "moderate",
        "stages": ["stage1", "stage2", "stage3", "stage4", "stage5"],
        "num_agents_per_stage": 4,
        "g1_per_stage": {"stage1": 2, "stage2": 2, "stage3": 2, "stage4": 2, "stage5": 2},
        "competence_per_stage": {"high": 2, "low": 2},
        "scope_per_stage": {"broad": 2, "narrow": 2},
        "stability_per_stage": {"stable": 2, "unstable": 2},
        "skill_ranges": {
            "broad": (0.55, 0.75),
            "narrow_focus": (0.85, 0.95),
            "narrow_other": (0.25, 0.50),
            "high_bonus": 0.10,
        },
        "cost_ranges": {
            "safe": (0.08, 0.12),
            "special": (0.15, 0.22),
        },
    }


def build_strong_family_spec() -> dict:
    return {
        "family_name": "strong",
        "generation_mode": "legacy_attribute_ranges",
        "stages": ["stage1", "stage2", "stage3", "stage4", "stage5"],
        "num_agents_per_stage": 4,
        "g1_per_stage": {"stage1": 1, "stage2": 2, "stage3": 2, "stage4": 3, "stage5": 3},
        "competence_per_stage": {"high": 2, "low": 2},
        "scope_per_stage": {"broad": 1, "narrow": 3},
        "stability_per_stage": {"stable": 2, "unstable": 2},
        "skill_ranges": {
            "broad": (0.55, 0.72),
            "narrow_focus": (0.90, 1.00),
            "narrow_other": (0.15, 0.45),
            "high_bonus": 0.10,
        },
        "cost_ranges": {
            "safe": (0.08, 0.14),
            "special": (0.18, 0.28),
        },
    }


def build_shared_basin_strong_family_spec() -> dict:
    return {
        "family_name": "shared_basin_strong",
        "generation_mode": "capability_shared_basin",
        "stages": ["stage1", "stage2", "stage3", "stage4", "stage5"],
        "num_agents_per_stage": 5,
        "profile_fields": {
            "competence_level": "capability",
            "scope_level": "capability",
            "stability_level": "capability",
        },
        "cost_ranges": {
            "uniform": (0.12, 0.16),
        },
        "semantic_skill_ranges": {
            "safe_core": {
                "anchor": (0.88, 0.95),
                "support": (0.58, 0.72),
                "background": (0.18, 0.30),
                "focus_fallback": (0.52, 0.66),
            },
            "mixed_shared": {
                "anchor": (0.79, 0.88),
                "support": (0.40, 0.56),
                "background": (0.12, 0.24),
                "focus_fallback": (0.34, 0.48),
            },
            "private_edge": {
                "anchor": (0.89, 0.97),
                "support": (0.22, 0.36),
                "background": (0.05, 0.14),
                "focus_fallback": (0.12, 0.24),
            },
            "private_barrier": {
                "anchor": (0.86, 0.94),
                "support": (0.34, 0.50),
                "background": (0.08, 0.18),
                "focus_fallback": (0.28, 0.42),
            },
            "edge_specialist": {
                "anchor": (0.88, 0.95),
                "support": (0.18, 0.28),
                "background": (0.04, 0.12),
                "focus_fallback": (0.08, 0.18),
            },
        },
        "stage_profiles": {
            "stage1": [
                {
                    "role": "safe_core_user_grounding",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage1_intake",
                    "allowed_next_labels": ["public_stage2_core", "mixed_stage2_lane"],
                    "anchor_caps": ["user_grounding", "account_lookup"],
                    "support_caps": ["line_resolution", "verification"],
                },
                {
                    "role": "safe_core_lookup_line",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage1_intake",
                    "allowed_next_labels": ["public_stage2_core", "mixed_stage2_lane"],
                    "anchor_caps": ["account_lookup", "line_resolution"],
                    "support_caps": ["user_grounding"],
                },
                {
                    "role": "safe_core_context_verify",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage1_intake",
                    "allowed_next_labels": ["public_stage2_core", "mixed_stage2_lane"],
                    "anchor_caps": ["user_grounding", "verification"],
                    "support_caps": ["account_lookup", "line_resolution"],
                },
                {
                    "role": "mixed_shared_edge_intake",
                    "g": 0,
                    "node_semantic": "mixed_shared",
                    "profile_kind": "shared_basin",
                    "route_label": "mixed_stage1_intake",
                    "allowed_next_labels": [
                        "public_stage2_core",
                        "mixed_stage2_lane",
                        "private_stage2_lane",
                        "private_barrier_stage2",
                    ],
                    "anchor_caps": ["user_grounding", "line_resolution"],
                    "anchor_boost": 0.06,
                    "support_caps": ["account_lookup", "verification"],
                },
                {
                    "role": "private_barrier_intake_gate",
                    "g": 1,
                    "node_semantic": "private_barrier",
                    "profile_kind": "barrier",
                    "route_label": "private_barrier_stage1",
                    "allowed_next_labels": [
                        "mixed_stage2_lane",
                        "private_stage2_lane",
                        "private_barrier_stage2",
                    ],
                    "anchor_caps": ["user_grounding", "account_lookup"],
                    "support_caps": ["line_resolution"],
                },
            ],
            "stage2": [
                {
                    "role": "safe_core_account_core",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage2_core",
                    "allowed_next_labels": [
                        "public_stage3_core",
                        "public_stage3_verify",
                    ],
                    "anchor_caps": ["account_lookup", "line_resolution"],
                    "anchor_boost": 0.04,
                    "support_caps": ["roaming_diagnosis", "verification"],
                },
                {
                    "role": "safe_core_line_core",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage2_core",
                    "allowed_next_labels": [
                        "public_stage3_edge",
                        "public_stage3_verify",
                        "mixed_stage3_lane",
                        "private_barrier_stage3",
                    ],
                    "anchor_caps": ["line_resolution"],
                    "anchor_boost": 0.01,
                    "support_caps": ["verification"],
                },
                {
                    "role": "mixed_shared_roaming_ready",
                    "g": 0,
                    "node_semantic": "mixed_shared",
                    "profile_kind": "shared_basin",
                    "route_label": "mixed_stage2_lane",
                    "allowed_next_labels": [
                        "public_stage3_edge",
                        "mixed_stage3_lane",
                        "private_barrier_stage3",
                    ],
                    "anchor_caps": ["roaming_diagnosis", "account_lookup"],
                    "anchor_boost": 0.11,
                    "support_caps": ["line_resolution", "verification"],
                },
                {
                    "role": "private_edge_roaming_lane",
                    "g": 0,
                    "node_semantic": "private_edge",
                    "profile_kind": "shared_basin",
                    "route_label": "private_stage2_lane",
                    "allowed_next_labels": [
                        "public_stage3_edge",
                        "mixed_stage3_lane",
                        "private_barrier_stage3",
                    ],
                    "anchor_caps": ["roaming_diagnosis", "line_resolution"],
                    "anchor_boost": 0.06,
                    "support_caps": ["verification"],
                },
                {
                    "role": "private_barrier_roaming_gate",
                    "g": 1,
                    "node_semantic": "private_barrier",
                    "profile_kind": "barrier",
                    "route_label": "private_barrier_stage2",
                    "allowed_next_labels": [
                        "public_stage3_edge",
                        "mixed_stage3_lane",
                        "private_barrier_stage3",
                    ],
                    "anchor_caps": ["account_lookup", "roaming_diagnosis"],
                    "support_caps": ["line_resolution"],
                },
            ],
            "stage3": [
                {
                    "role": "safe_core_network_core",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage3_core",
                    "allowed_next_labels": ["public_stage4_core"],
                    "anchor_caps": ["network_diagnosis", "permission_diagnosis"],
                    "support_caps": ["verification", "repair_execution"],
                },
                {
                    "role": "safe_core_network_verify",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage3_verify",
                    "allowed_next_labels": ["public_stage4_core"],
                    "anchor_caps": ["network_diagnosis", "verification"],
                    "support_caps": ["permission_diagnosis", "apn_diagnosis"],
                },
                {
                    "role": "mixed_shared_edge_diagnosis",
                    "g": 0,
                    "node_semantic": "mixed_shared",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage3_edge",
                    "allowed_next_labels": ["public_stage4_verify", "mixed_stage4_lane"],
                    "anchor_caps": ["apn_diagnosis", "verification"],
                    "anchor_boost": 0.07,
                    "support_caps": ["network_diagnosis", "permission_diagnosis"],
                },
                {
                    "role": "private_edge_config_lane",
                    "g": 0,
                    "node_semantic": "private_edge",
                    "profile_kind": "shared_basin",
                    "route_label": "mixed_stage3_lane",
                    "allowed_next_labels": [
                        "public_stage4_verify",
                        "mixed_stage4_lane",
                        "private_stage4_lane",
                        "private_barrier_stage4",
                    ],
                    "anchor_caps": ["network_diagnosis", "apn_diagnosis", "roaming_diagnosis"],
                    "anchor_boost": 0.12,
                    "support_caps": ["verification"],
                },
                {
                    "role": "private_barrier_config_gate",
                    "g": 1,
                    "node_semantic": "private_barrier",
                    "profile_kind": "barrier",
                    "route_label": "private_barrier_stage3",
                    "allowed_next_labels": [
                        "public_stage4_verify",
                        "mixed_stage4_lane",
                        "private_stage4_lane",
                        "private_barrier_stage4",
                    ],
                    "anchor_caps": ["network_diagnosis", "apn_diagnosis", "roaming_diagnosis"],
                    "anchor_boost": 0.09,
                    "support_caps": ["verification"],
                },
            ],
            "stage4": [
                {
                    "role": "safe_core_repair_core",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage4_core",
                    "allowed_next_labels": ["public_stage5_verify", "public_stage5_decision"],
                    "anchor_caps": ["repair_execution", "permission_diagnosis"],
                    "anchor_boost": 0.0,
                    "support_caps": ["verification", "terminal_decision"],
                },
                {
                    "role": "safe_core_repair_verify",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage4_verify",
                    "allowed_next_labels": ["public_stage5_verify", "public_stage5_decision"],
                    "anchor_caps": ["repair_execution", "verification"],
                    "anchor_boost": 0.03,
                    "support_caps": ["permission_diagnosis", "apn_diagnosis", "terminal_decision"],
                },
                {
                    "role": "mixed_shared_repair_escalation",
                    "g": 0,
                    "node_semantic": "mixed_shared",
                    "profile_kind": "shared_basin",
                    "route_label": "mixed_stage4_lane",
                    "allowed_next_labels": [
                        "public_stage5_verify",
                        "public_stage5_decision",
                        "mixed_stage5_transfer",
                        "private_stage5_edge",
                    ],
                    "anchor_caps": ["repair_execution", "terminal_decision"],
                    "anchor_boost": 0.09,
                    "support_caps": ["verification"],
                },
                {
                    "role": "private_edge_repair_lane",
                    "g": 0,
                    "node_semantic": "private_edge",
                    "profile_kind": "shared_basin",
                    "route_label": "private_stage4_lane",
                    "allowed_next_labels": [
                        "public_stage5_verify",
                        "mixed_stage5_transfer",
                        "private_stage5_edge",
                        "private_stage5_leaf",
                    ],
                    "anchor_caps": ["repair_execution", "apn_diagnosis"],
                    "anchor_boost": 0.08,
                    "support_caps": ["verification", "terminal_decision", "roaming_diagnosis"],
                },
                {
                    "role": "private_barrier_edge_repair",
                    "g": 1,
                    "node_semantic": "private_barrier",
                    "profile_kind": "barrier",
                    "route_label": "private_barrier_stage4",
                    "allowed_next_labels": [
                        "public_stage5_decision",
                        "private_stage5_edge",
                        "private_stage5_leaf",
                    ],
                    "anchor_caps": ["repair_execution", "terminal_decision", "apn_diagnosis"],
                    "anchor_boost": 0.09,
                    "support_caps": ["verification", "terminal_decision", "roaming_diagnosis"],
                },
            ],
            "stage5": [
                {
                    "role": "safe_core_verify_core",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage5_verify",
                    "anchor_caps": ["verification", "repair_execution"],
                    "anchor_boost": 0.02,
                    "support_caps": ["terminal_decision"],
                },
                {
                    "role": "safe_core_decision_core",
                    "g": 0,
                    "node_semantic": "safe_core",
                    "profile_kind": "shared_basin",
                    "route_label": "public_stage5_decision",
                    "anchor_caps": ["terminal_decision", "verification"],
                    "anchor_boost": 0.02,
                    "support_caps": ["repair_execution"],
                },
                {
                    "role": "mixed_shared_transfer_ready",
                    "g": 0,
                    "node_semantic": "mixed_shared",
                    "profile_kind": "shared_basin",
                    "route_label": "mixed_stage5_transfer",
                    "anchor_caps": ["repair_execution", "terminal_decision", "verification"],
                    "anchor_boost": 0.07,
                    "support_caps": ["verification"],
                },
                {
                    "role": "private_edge_resolution",
                    "g": 0,
                    "node_semantic": "private_edge",
                    "profile_kind": "shared_basin",
                    "route_label": "private_stage5_edge",
                    "anchor_caps": ["repair_execution", "verification"],
                    "anchor_boost": 0.07,
                    "support_caps": ["terminal_decision"],
                },
                {
                    "role": "private_leaf_transfer_edge",
                    "g": 1,
                    "node_semantic": "edge_specialist",
                    "profile_kind": "specialist",
                    "route_label": "private_stage5_leaf",
                    "anchor_caps": ["verification", "terminal_decision"],
                    "anchor_boost": 0.14,
                    "support_caps": ["repair_execution"],
                },
            ],
        },
    }
